- title: Mentoring
  desc: Becoming a Tech-Leader
  icon: assets/images/services-icon-java.png

- title: Consulting
  desc: IT Infrastructure, Software Development, DevOps
  icon: assets/images/services-icon-brush.png

- title: Outsourcing and Recruiting
  desc: Finding the right IT experts for you
  icon: assets/images/services-icon-coding.png
